<?php

namespace ResourceCatalog\Model;

interface IResourceCatalog extends IResourceCatalogTypeName, IResourceCatalogTypeIdentify, IResourceCatalogTypeEnName, IResourceCatalogTypeDoublePublicity, IResourceCatalogTypeRedBlackList, IResourceCatalogIsConfirm
{
    public const TYPE = array(
        'NULL' => 0,
        'XBXZCF' => 1,
        'XBXZXK' => 2,
        'SXBZXRMD' => 3,
        'FRXX' => 4,
        'QIYEJBXX' => 5,
        'GTGSHXX' => 6,
        'CMQYSBXX' => 7,
        'YPLSQYXX' => 8,
        'JGRYXX' => 9,
        'SXQYHMD' =>10,
        'SPYPTSJBJLGR' => 11,
        'SPYPTSJBJLDW' => 12,
        'HNMPCPXX' => 13,
        'QYYCMLXX' => 14,
        'QYZXXX' => 15,
        'QYDXXX' => 16,
        'CCJCJGXX' => 17,
        'JGJCDXZJL' => 18,
        'YSCRJZJJJZGRDXX' => 19,
        'JDCWFXX' => 20,
        'JSZGXX' => 21,
        'SJYXXS' => 22,
        'JYJGXINXI' => 23,
        'GRRYXXJYJ' => 24,
        'JGRYXXSJYJ' => 25,
        'ESCJDPGJGHZZS' => 26,
        'ZYJNZSXX' => 27,
        'YLBXXX' => 28,
        'YZTQSBXXHMD' => 29,
        'SYBXXX' => 30,
        'SBQYXX' => 31,
        'GZRYXX' => 32,
        'YZTQNMGGZHMD' => 33,
        'SLYSXKZXX' => 34,
        'GRRYXXJTJ' => 35,
        'QYGSZXXX' => 36,
        'AJNSRXX' => 37,
        'ZDSSWFAJXX' => 38,
        'QYDSXZCFXX' => 39,
        'SHZZNJXX' => 40,
        'GRRYXXMZJ' => 41,
        'MBFQYML' => 42,
        'SHTTDJXX' => 43,
        'SFJDJGCYRYZGXX' => 44,
        'SFJDJGDJXX' => 45,
        'GZJGJBXX' => 46,
        'GZYXX' => 47,
        'JCFLFWSXX' => 48,
        'JCFLFWGZZJBXX' => 49,
        'LSSWSXX' => 50,
        'LSZYZGZXX' => 51,
        'JGRYXXSSFJ' => 52,
        'SJQYJSZXRDXX' => 53,
        'ZFCGDLJGXX' => 54,
        'SLGCZBXX' => 55,
        'GJJLTQYRZXX' => 56,
        'DTJXJGRXX' => 57,
        'TJDCDXML' => 58,
        'HNSZLJDW' => 59,
        'XSPJXX' => 60,
        'SXBZXJGXX' => 61,
        'SJJXMXX' => 62,
        'XZXKQYXX' => 63,
        'QSLHXJJTJL' => 64,
        'SPFYSXK' => 65,
        'FDCKFQYZZXX' => 66,
        'JGRYXXSFGJ' => 67,
        'XYTXHMD' => 68,
        'SYDWJBXX'=>69,
        'XZZSXX' => 71,
        'XZJFXX' => 74,
        'QTXZZFXX' => 77,
        'HEIMDXX' => 78,
        'HONGMDXX' => 79,
        'HYFJFLJG' => 80,
        'QYHYSJ' => 81,
        'DWYSZCXX'=>82,
        'TQMYQYZK'=>83,
        'ZFCGHT'=>84,
        'GGZYJYHT'=>85,
        'GQCGHT'=>86,
        'GCJSHT'=>87,
        'QTHT'=>88,
        'CCJCJG'=>89,
        'XYSFSQ'=>90,
        'QYFRGGXYZHPJJG' => 91,
        'YSZYZGXX' => 92,
        'XZCJ'=>93,
        'XZJDJC'=>94,
        'XZJL'=>95,
        'XZQR'=>96,
        'XZQZ'=>97,
        //@position_type_98
        'TEST' => 500
    );

    public const USERGROUP_TYPE_RELATIONSHIP = array(
        IUserGroup::ID['NULL'] => array(
            self::TYPE['TEST'],
            self::TYPE['XBXZCF'],
            self::TYPE['XBXZXK'],
            self::TYPE['CCJCJG'],
            self::TYPE['XZQZ'],
            self::TYPE['XZQR'],
            self::TYPE['XZJL'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZCJ'],
        ),
        IUserGroup::ID['FGW'] => array(
            self::TYPE['JGJCDXZJL'],
            self::TYPE['SJJXMXX'],
            self::TYPE['SYDWJBXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
            self::TYPE['QYFRGGXYZHPJJG'],
        ),

        IUserGroup::ID['XSCJGJ'] => array(
            self::TYPE['QIYEJBXX'],
        ),
        IUserGroup::ID['XZFBGS'] => array(),
        IUserGroup::ID['XXZSPJ'] => array(),
        IUserGroup::ID['XZRZYJ'] => array(),
        IUserGroup::ID['XXFJ'] => array(),
        IUserGroup::ID['XXCZXJ'] => array(),
        IUserGroup::ID['XSFJ'] => array(
            self::TYPE['LSZYZGZXX'],
            self::TYPE['GZYXX'],
            self::TYPE['SFJDJGCYRYZGXX'],
        ),
        IUserGroup::ID['XJTJ'] => array(),
        IUserGroup::ID['XGXJ'] => array(),
        IUserGroup::ID['XYJJ'] => array(),
        IUserGroup::ID['XRSJ'] => array(
            self::TYPE['GZRYXX'],
        ),
        IUserGroup::ID['XSJJ'] => array(),
        IUserGroup::ID['XYBJ'] => array(),
        IUserGroup::ID['XCZJ'] => array(),
        IUserGroup::ID['XGAJ'] => array(),
        IUserGroup::ID['XJYTYJ'] => array(
            self::TYPE['JSZGXX'],
        ),
        IUserGroup::ID['XTYJRJ'] => array(),
        IUserGroup::ID['XWJW'] => array(
            self::TYPE['YSZYZGXX'],
        ),
        IUserGroup::ID['XMZJ'] => array(
            self::TYPE['SHTTDJXX'],
        ),
        IUserGroup::ID['XTJJ'] => array(),
        IUserGroup::ID['XWLJ'] => array(),
        IUserGroup::ID['XNYNCJ'] => array(),
        IUserGroup::ID['XSTJ'] => array(),
        IUserGroup::ID['XZJJ'] => array(),
        IUserGroup::ID['XSLJ'] => array(),
        IUserGroup::ID['MFZRMZF'] => array(),
        IUserGroup::ID['JCZRMZF'] => array(),
        IUserGroup::ID['QDZRMZF'] => array(),
        IUserGroup::ID['YKZRMZF'] => array(),
        IUserGroup::ID['BWDZRMZF'] => array(),
        IUserGroup::ID['DWRMZF'] => array(),
        //@position_usergroup
    );

    public const STATUS_NORMAL = 0;

    public const STATUS_DELETE = -2;
}
